# Generated by Django 4.2.1 on 2023-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMC5006',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('area_yard', models.FloatField()),
                ('area_feet', models.FloatField()),
            ],
        ),
    ]
