# Generated by Django 4.2.1 on 2023-07-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmc5006',
            options={'verbose_name_plural': 'DMC5600'},
        ),
    ]
