# Generated by Django 4.2.1 on 2023-07-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourProject', '0002_alter_dmc5006_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DMC5006',
        ),
    ]
